### ISSUE TITLE
Make hide/show annotation hidden by default and a sticky preference

### ISSUE THREAD

**Issue by jdlrobson** [jdlrobson/mediawiki-skins-skinjson#10]
The annotations we show can be quite heavy and might get in the way of skin development at certain times. I think they should probably default to hidden so we don't have to continuously uninstall in LocalSettings.php.

Suggestions
[]  This should be the default state:
<img width="1432" alt="Screen Shot 2022-06-23 at 2 25 39 PM" src="https://user-images.githubusercontent.com/148752/175405116-11819d30-817b-4f2a-9c1d-3123e066df70.png">
[] If I click "show" and refresh the page, the annotations should remain visible

@alistair3149 what do you think?

**Comment by malberts** [comment]
I would prefer them being hidden by default. So far I've turned those off (or removed from LocalSettings) more often than I've needed to see them.

**Comment by alistair3149** [comment]
I would work on a quick PR tomorrow to make it hidden by default.

**Comment by alistair3149** [comment]
With the recent PR there is still the issue where the styles are not being loaded in the special pages. I am not sure how to tackle it.

**Comment by jdlrobson** [comment]
Fixed special page issue in 2fbb0e50f16f294
