### ISSUE TITLE
Issues with config value SkinJSONValidate

### ISSUE THREAD

**Issue by holybiber** [jdlrobson/mediawiki-skins-skinjson#16]
I installed SkinJSON to help me in skin development (thanks for the tool!) but then I noticed weird contents of `html-after-portal` elements everywhere, they were always the same:
`<div class=\"after-portlet after-portlet-personal\"><div title=\"($name === &quot;personal&quot;)\" class=\"skin-json-hook-validation-element skin-json-hook-validation-element-SkinAfterPortlet skin-json-validation-element skin-json-validation-element-block\" data-hook=\"SkinAfterPortlet\"><a href=\"//www.mediawiki.org/wiki/Manual:Hooks/SkinAfterPortlet\" title=\"View documentation on MediaWiki.org\"><div class=\"skin-json-validation-element__title\">SkinAfterPortlet</div><div class=\"skin-json-validation-element__description\">($name === \"personal\")</div></a></div></div>`
After investigating it a bit I could trace it to `SkinJSON::onSkinAfterPortlet()`. I could get rid of this behavior by setting `SkinJSONValidate` to `false` in SkinJSON's skin.json. Now my `html-after-portal` elements are empty strings which seems to be correct.

This seems to be a bug to me. I didn't investigate further what SkinJSONValidate is meant for but I'd suggest this variable should be set to `false` by default in the configuration.

**Comment by holybiber** [comment]
Just realizing that with `SkinJSONValidate` set to false I know have an extra `⧼skin-json-hook-validation-sidebar-item⧽` in the sidebar and `⧼skin-json-hook-validation-user-menu⧽` in the user menu, so that isn't really a solution.

**Comment by jdlrobson** [comment]
Does $wgSkinJSONDebug = false; help?

**Comment by jdlrobson** [comment]
I guess this is advanced behavior so agree it probably should be disabled by default.

**Comment by holybiber** [comment]
> Does $wgSkinJSONDebug = false; help?

No, it doesn't. With `SkinJSONValidate = true` I still have the wrongly filled `html-after-portal` elements in the skinjson view and when it's false I have e.g. this `⧼skin-json-hook-validation-sidebar-item⧽` visible in the sidebar.
