### ISSUE TITLE
MW 1.35 compatibility

### ISSUE THREAD

**Issue by malberts** [jdlrobson/mediawiki-skins-skinjson#5]
The minimum MW version was bumped to 1.38 recently. Do you plan on adding non-backward compatible changes going forward?
At the moment the latest master is still working with 1.35 as far as I can tell (after manually changing the requirement). I'm working on a Mustache-based skin where I need to maintain 1.35 compatibility and I found this debug skin to be quite useful. I know I can just freeze what I have (or manually change the version), but I'd prefer to track whatever you do.

If you have no objections, can we drop the minimum version back to 1.35 and then I can try to shim whatever new things you add?

**Comment by jdlrobson** [comment]
I only bumped the version to avoid the skin from showing up in user preferences as a selectable skin as support for https://github.com/jdlrobson/mediawiki-skins-skinjson/blob/8ae886db0645147a7ca3d77cc1507f70c2d4570b/skin.json#L16 was only added recently.

I believe you can drop the skin requirement quite safely. It shouldn't effect your own use case.
